/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.BorderLayout;
import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Carlos
 */
public class Graficos extends javax.swing.JFrame {

    private ArrayList<Integer> datosXEcalabilidad = new ArrayList<Integer>();
    private ArrayList<Integer> datosYEscalabilidad = new ArrayList<Integer>();
    
    private ArrayList<Integer> datosXVecino = new ArrayList<Integer>();
    private ArrayList<Integer> datosYVecino = new ArrayList<Integer>();
    
    private ArrayList<Integer> datosXCuello = new ArrayList<Integer>();
    private ArrayList<Integer> datosYCuello = new ArrayList<Integer>();
    
    private ArrayList<Integer> datosYThroughput = new ArrayList<Integer>();
    
    public Graficos(ArrayList<Integer> datosXEcalabilidad, ArrayList<Integer> datosYEscalabilidad, 
        ArrayList<Integer> datosXVecino, ArrayList<Integer> datosYVecino, ArrayList<Integer> datosXCuello, 
        ArrayList<Integer> datosYCuello, ArrayList<Integer> datosYThroughput) {
        
        initComponents();
        
        this.datosXEcalabilidad = datosXEcalabilidad;
        this.datosYEscalabilidad = datosYEscalabilidad;
        
        this.datosXVecino = datosXVecino;
        this.datosYVecino = datosYVecino;
        
        this.datosXCuello = datosXCuello;
        this.datosYCuello = datosYCuello;
        
        this.datosYThroughput = datosYThroughput;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escalabilidadB = new javax.swing.JButton();
        vecinosB = new javax.swing.JButton();
        botellaB = new javax.swing.JButton();
        throughputB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Análisis con gráficos");
        setLocationByPlatform(true);
        setResizable(false);

        escalabilidadB.setText("Escalabilidad");
        escalabilidadB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalabilidadBActionPerformed(evt);
            }
        });

        vecinosB.setText("Variación de vecinos");
        vecinosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vecinosBActionPerformed(evt);
            }
        });

        botellaB.setText("Cuellos de botella");
        botellaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botellaBActionPerformed(evt);
            }
        });

        throughputB.setText("Throughput");
        throughputB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throughputBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escalabilidadB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vecinosB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botellaB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(throughputB, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(throughputB, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(botellaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vecinosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escalabilidadB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void escalabilidadBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escalabilidadBActionPerformed
        XYSeries oSeries =  new XYSeries("Aumento de mensajes");
        
        for(int i = 0; i < datosXEcalabilidad.size(); i++){
            oSeries.add(datosXEcalabilidad.get(i),datosYEscalabilidad.get(i));
        }
        
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(oSeries);
        
        JFreeChart grafico = ChartFactory.createXYLineChart("Aumento de mensajes","Numero de vecinos","Latencia Global",dataset);
        ChartPanel panel = new ChartPanel(grafico);
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel);
        jPanel1.validate();
    }//GEN-LAST:event_escalabilidadBActionPerformed

    private void vecinosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vecinosBActionPerformed
        XYSeries oSeries =  new XYSeries("Escalabilidad");
        
        for(int i = 0; i < datosXVecino.size(); i++){
            oSeries.add(datosXVecino.get(i),datosYVecino.get(i));
        }
        
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(oSeries);
        
        JFreeChart grafico = ChartFactory.createXYLineChart("Escalabilidad","Clientes","Latencia Global",dataset);
        ChartPanel panel = new ChartPanel(grafico);
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel);
        jPanel1.validate();
    }//GEN-LAST:event_vecinosBActionPerformed

    private void botellaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botellaBActionPerformed
        XYSeries oSeries =  new XYSeries("Cuellos de botella");
        
        for(int i = 0; i < datosXCuello.size(); i++){
            oSeries.add(datosXCuello.get(i),datosYCuello.get(i));
        }
        
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(oSeries);
        
        JFreeChart grafico = ChartFactory.createXYLineChart("Cuellos de botella","Grupo","Latencia de grupo",dataset);
        ChartPanel panel = new ChartPanel(grafico);
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel);
        jPanel1.validate();
    }//GEN-LAST:event_botellaBActionPerformed

    private void throughputBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throughputBActionPerformed
        XYSeries oSeries =  new XYSeries("Throughput");
        
        for(int i = 0; i < datosXVecino.size(); i++){
            oSeries.add(datosXVecino.get(i),datosYThroughput.get(i));
        }
        
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(oSeries);
        
        JFreeChart grafico = ChartFactory.createXYLineChart("Throughput","Numero de vecinos","Latencia Global",dataset);
        ChartPanel panel = new ChartPanel(grafico);
        
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel);
        jPanel1.validate();
    }//GEN-LAST:event_throughputBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botellaB;
    private javax.swing.JButton escalabilidadB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton throughputB;
    private javax.swing.JButton vecinosB;
    // End of variables declaration//GEN-END:variables
}
